---
# tasks file for update_system
- name: "Update Packages"
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
      - "{{ ansible_distribution }}.yml"
      - "{{ ansible_os_family }}.yml"
