---
- name: "Test Inputvariable"
  become: true
  become_user: ubuntu
  hosts: all
  tasks:
    - name: "Install something"
      ansible.builtin.apt:
        name: "{{ PACKAGE_NAME }}"
        state: latest
